<#
.Synopsis
This funtion formats a header section for the output generated by the Get-PsUserPermissions function and returns it as a single string.

.Description
This function returns a formatted string that contains a header block whose intent is to describe the server from which the permissions originate,
the source user ($FromUser) whose permissions are to be cloned and the destination user ($ToUser) who will receive the new permissions.

.Parameter ServerInstance
This is the name of the server that will receive the snap mount.

.Parameter FromUser
This is the name of the user from which permissions will be cloned.

.Parameter ToUser
This is the name of the user who will receive the new cloned permissions.

.Example
.
Get-Header | out-file -Path "c:\scripts\script_file.sql" -Append

This will append a header block to the "c:\scripts\script_file.sql" file.

.Example
.
Get-Header

This will send a header block to the standard output device, usually the screen.
#>
function Get-Header {
    [cmdletbinding()]

    param(
        [Parameter(Mandatory=$true)]
        [string] $SourceServer
        ,
        [Parameter(Mandatory=$true)]
        [string] $FromUser
        ,
        [Parameter(Mandatory=$true)]
        [string] $ToUser
        )

    $header_width = 100
    $header_tail = "======"
    $src_svr = "$("--======                       Source Server: $SourceServer".PadRight($header_width-$header_tail.Length, ' '))$header_tail`n"
    $src_usr = "$("--======                       Source User..: $FromUser".PadRight($header_width-$header_tail.Length, ' '))$header_tail`n"
    $trg_usr = "$("--======                       Target User..: $ToUser".PadRight($header_width-$header_tail.Length, ' '))$header_tail`n"
    $dt_str =  "$("--======                       Date.........: $(Get-Date)".PadRight($header_width-$header_tail.Length, ' '))$header_tail`n"
    $header_title = "$("--======                         CLONE USER'S PERMISSIONS SCRIPT".PadRight($header_width-$header_tail.Length, ' '))$header_tail`n"
    $header_for = "$("--======                                      for".PadRight($header_width-$header_tail.Length, ' '))$header_tail`n"
    $header =  "$('--'.PadRight($header_width, '='))`n"
    $header += $header_title
    $header += $header_for
    $header += $src_svr
    $header += $src_usr
    $header += $trg_usr
    $header += $dt_str
    $header += "$('--'.PadRight($header_width, '='))`n"

    $header
    }
